### ISSUE TITLE
Panic when used in async application

### ISSUE THREAD

**Issue by rgreinho** [hunger/downloader#11]
I have a small async application which needs to download a bunch of files, therefore I decided to use this library to re-implement the downloading part. 

It worked fairly well, except that at the end of the downloads it fails with the following message:
```
The application panicked (crashed).
Message:  Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```

This line https://github.com/hunger/downloader/blob/0.2.6/src/backend.rs#L168 seems to be the culprit, but I am not entirely sure how to workaround it.

I am using the following dependencies for `downloader` and `tokio`:
```toml
downloader = { version = "0.2.6", features = ["tui", "verify"]}
tokio = { version = "1.12.0", features = ["full"] }
```
